// agents
export const AGENTS_RECEIVED = 'AGENTS_RECEIVED';
export const AGENTS_CLEAR = 'AGENTS_CLEAR';
export const AGENTS_SET_DISPLAY_MODAL_ID = 'AGENTS_SET_DISPLAY_MODAL_ID';
export const AGENTS_SET_INPUT_RESOURCES = 'AGENTS_SET_INPUT_RESOURCES';
